### ISSUE TITLE
`sd_metrics_params` option

### ISSUE THREAD

**Issue by supercaracal** [aws/amazon-cloudwatch-agent#1444]
We use some Apache Solr containers on AWS ECS Fargate and collect their metrics via a CloudWatch agent. The endpoint needs a query string parameter for the Prometheus output.

https://solr.apache.org/guide/solr/latest/deployment-guide/monitoring-with-prometheus-and-grafana.html#metrics-api-with-prometheus-format

However, it looks to me like we can't specify the `params` option to the agent setting.
https://github.com/aws/amazon-cloudwatch-agent/blob/main/internal/ecsservicediscovery/README.md

Is there a way to be able to specify the `params` option related to Prometheus like this?

```json
{
  "agent": {
    "debug": true
  },
  "logs": {
    "metrics_collected": {
      "prometheus": {
        "prometheus_config_path": "env:PROMETHEUS_CONFIG_CONTENT",
        "log_group_name": "/aws/ecs/containerinsights/foo/prometheus",
        "ecs_service_discovery": {
          "sd_frequency": "1m",
          "sd_result_file": "/tmp/cwagent_ecs_auto_sd.yaml",
          "sd_target_cluster": "foo",
          "sd_cluster_region": "ap-northeast-1",
          "service_name_list_for_tasks": [
            {
              "sd_job_name": "solr",
              "sd_metrics_path": "/solr/admin/metrics",
              "sd_metrics_params": { "wt": "prometheus" },
              "sd_metrics_ports": "8983",
              "sd_service_name_pattern": "^solr$"
            }
          ]
        },
        "emf_processor": {
          "metric_declaration_dedup": true,
          "metric_namespace": "ECS/CustomMetrics",
          "metric_declaration": [
            {
              "source_labels": ["ServiceName"],
              "label_matcher": "^solr$",
              "dimensions": [["ClusterName", "ServiceName", "TaskId"]],
              "metric_selectors": ["^solr_"]
            }
          ]
        }
      }
    }
  }
}
```

```yaml
---
global:
  scrape_interval: 1m
  scrape_timeout: 10s
scrape_configs:
  - job_name: cwagent-ecs-file-sd-config
    sample_limit: 10000
    file_sd_configs:
      - files: ["/tmp/cwagent_ecs_auto_sd.yaml"]
```
