### ISSUE TITLE
cloudwatch agent in docker ECS and host metrics *ethtool*

### ISSUE THREAD

**Issue by boostrack** [aws/amazon-cloudwatch-agent#165]
This is basically some question in regards to documentation on how to monitor EC2 instance deploying cw agent as ECS daemon task.

I have this currently working but not in an optimal way. Is not clear to me or had found any docs on the best practice to do achieve this.

I would like to enable **ethtool** Network performance metrics  but not sure how can I achieve this.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-network-performance.html

With telegraf one can do something like

```
 environment:
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_MOUNT_PREFIX: /hostfs
    volumes:
      - /etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /var/run/utmp:/var/run/utmp:ro
 ```

Is this something supported by cw agent version of telegraf ? or how can this be possible.

The most relevant doc I had found so far is https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/deploy-container-insights-ECS-instancelevel.html

Either way .. I am not getting any metrics related to **ethtool** being from host or container so I guess that is seeing  container networking and as it does not see ENA interface reports no metrics.. is this possible to achieve and if so how?
```
"metrics": {
    "append_dimensions": {
      "InstanceId": "${aws:InstanceId}"
    },
    "metrics_collected": {
      "ethtool": {
        "interface_include": [
          "eth0",
          "en5"
        ],
        "metrics_include": [
          "rx_packets",
          "tx_packets",
          "bw_in_allowance_exceeded",
          "bw_out_allowance_exceeded",
          "conntrack_allowance_exceeded",
          "linklocal_allowance_exceeded",
          "pps_allowance_exceeded"
         ]
    }
 }
```

Thanks
