### ISSUE TITLE
PodName of a pod from a job is incorrectly truncated

### ISSUE THREAD

**Issue by victornoel** [aws/amazon-cloudwatch-agent#234]
I have jobs named like so with dashes in it:
- `some-prefix.some-middle-name.a-name`
- `some-prefix.some-middle-name.another-name`
- `some-prefix.some-other-name.a-name`
- `other-prefix.some-name.name`
- etc

And it creates pods as expected with the following names `some-prefix.some-middle-name.a-name-vmrpg` and so on.

Obviously we would like that the inferred name for the pod to be the name of the job itself, but in practice, it gets to be `some` or `other`. As you can imagine, this is quite useless to be able to use effectively the information exported by cloudwatch agent :)

Is that desired? It looks to be a bug for me.

**Comment by pxaws** [comment]
Could you share the deployment yaml file so that we understand how the pod name is composed? The logic for parsing the pod name from job is here: https://github.com/aws/amazon-cloudwatch-agent/blob/ae7730ceeea112b2fc6cda79d45b32a7ea6dadaa/plugins/processors/k8sdecorator/stores/podstore.go#L555-L561. I would expect `some-prefix.some-middle-name.a-name-vmrpg` gives a pod name of `some-prefix.some-middle-name.a-name` instead based on code.

**Comment by victornoel** [comment]
@pxaws thank you. Some more context: we are using the images `amazon/cloudwatch-agent:1.247346.1b249759` and `amazon/aws-for-fluent-bit:latest`.

here is the job description (I dropped some parts related to the container themselves):
```yaml
kind: Job
apiVersion: batch/v1
metadata:
  name: staging-eu.demo-poc.execution-engine
  namespace: prod
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  selector:
    matchLabels:
      controller-uid: d9b5511f-2c17-4c85-b4dd-32bb97e5c54f
  template:
    metadata:
      labels:
        controller-uid: d9b5511f-2c17-4c85-b4dd-32bb97e5c54f
        job-name: staging-eu.demo-poc.execution-engine
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
    spec:
      volumes:
        - name: secrets
          secret:
            secretName: staging-eu.demo-poc.execution-engine
            defaultMode: 420
      containers: {}
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
```

and here is the generated event arriving in AWS Cloudwatch:
```json
{
  "AutoScalingGroupName": "tf-asg-20210201122947719400000005",
  "CloudWatchMetrics": [
    {
      "Metrics": [
        {
          "Unit": "Percent",
          "Name": "pod_memory_utilization"
        },
        {
          "Unit": "Percent",
          "Name": "pod_memory_utilization_over_pod_limit"
        }
      ],
      "Dimensions": [
        [
            "PodName",
            "Namespace",
            "ClusterName"
        ],
        [
            "Namespace",
            "ClusterName"
        ],
        [
            "ClusterName"
        ]
      ],
      "Namespace": "ContainerInsights"
    },
    {
      "Metrics": [
        {
          "Unit": "Percent",
          "Name": "pod_memory_reserved_capacity"
        }
      ],
      "Dimensions": [
        [
            "PodName",
            "Namespace",
            "ClusterName"
        ],
        [
            "ClusterName"
        ]
      ],
      "Namespace": "ContainerInsights"
    }
  ],
  "ClusterName": "eks-1",
  "InstanceId": "i-0089bee0cd875ba89",
  "InstanceType": "m5a.4xlarge",
  "Namespace": "prod",
  "NodeName": "ip-10-0-4-188.eu-west-1.compute.internal",
  "PodName": "staging",
  "Sources": [
      "cadvisor",
      "pod",
      "calculated"
  ],
  "Timestamp": "1624256959989",
  "Type": "Pod",
  "Version": "0",
  "kubernetes": {
    "host": "ip-10-0-4-188.eu-west-1.compute.internal",
    "labels": {
      "controller-uid": "dfcd1d64-8438-49e5-91db-90b77efab444",
      "job-name": "staging-eu.demo-poc.execution-engine"
    },
    "namespace_name": "prod",
    "pod_id": "8be6d5ca-3caf-4c89-81ed-fc87bb6408fb",
    "pod_name": "staging-eu.demo-poc.execution-engine-el5hnz",
    "pod_owners": [
      {
        "owner_kind": "Job",
        "owner_name": "staging"
      }
    ]
  },
  "pod_memory_cache": 0,
  "pod_memory_failcnt": 0,
  "pod_memory_limit": 8589934592,
  "pod_memory_mapped_file": 0,
  "pod_memory_max_usage": 1546878976,
  "pod_memory_request": 8589934592,
  "pod_memory_reserved_capacity": 12.943974060106916,
  "pod_memory_rss": 1537024000,
  "pod_memory_swap": 0,
  "pod_memory_usage": 1546125312,
  "pod_memory_utilization": 2.329771148979281,
  "pod_memory_utilization_over_pod_limit": 17.998886108398438,
  "pod_memory_working_set": 1546092544,
  "pod_number_of_containers": 1,
  "pod_number_of_running_containers": 1,
  "pod_status": "Running"
}
```
