### ISSUE TITLE
InvalidParameterValue: The parameter MetricData.member.20.Dimensions.member.4.Value must be shorter than 257 characters

### ISSUE THREAD

**Issue by skadem07** [aws/amazon-cloudwatch-agent#240]
We are using amazon cloudwatch container insights to get the pod level metrics , but we also wanted to get instance level metrics , so i changed my config to get mem_used_percent, but although with the below config i'm able to get the metrics , but the logs show 404 InvalidParameterValue error. 

I believe this could be because of the name of the instances, as i don't see these logs on all pods, 

I don't see this error when on the instance with the name:  `xxx-eks18-system-xxx-eks18-eks_asg` (which has 34 characters) , anything above 34 characters has this parameter value error. 

```
+ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Configmap:

```
apiVersion: v1
data:
  # Configuration is in Json format. No matter what configure change you make,
  # please keep the Json blob valid.
  cwagentconfig.json: |
    {
      "metrics":{
            "append_dimensions":{
               "InstanceId":"${aws:InstanceId}"
            },
            "metrics_collected":{
               "disk":{
                  "measurement":[
                     "used_percent",
                     "disk_free"
                  ],
                  "metrics_collection_interval":60,
                  "resources":[
                     "*"
                  ]
               },
               "mem":{
                  "measurement":[
                     "mem_used_percent"
                  ],
                  "metrics_collection_interval":60
               }
            }
         },
      "logs": {
        "metrics_collected": {
          "kubernetes": {
            "cluster_name": "amp-eks18",
            "metrics_collection_interval": 60
          }
        },
        "force_flush_interval": 5
      }
    }
kind: ConfigMap
metadata:
  name: cwagentconfig
  namespace: amazon-cloudwatch
```

Daemonset :

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudwatch-agent
  namespace: amazon-cloudwatch
spec:
  selector:
    matchLabels:
      name: cloudwatch-agent
  template:
    metadata:
      labels:
        name: cloudwatch-agent
    spec:
      tolerations:
        - operator: Exists
      containers:
        - name: cloudwatch-agent
          image: amazon/cloudwatch-agent:1.247348.0b251302 
          #ports:
          #  - containerPort: 8125
          #    hostPort: 8125
          #    protocol: UDP
          resources:
            limits:
              cpu:  200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
          # Please don't change below envs
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CI_VERSION
              value: "k8s/1.3.7" 
          # Please don't change the mountPath
          volumeMounts:
            - name: cwagentconfig
              mountPath: /etc/cwagentconfig
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
            - name: dockersock
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: varlibdocker
              mountPath: /var/lib/docker
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: devdisk
              mountPath: /dev/disk
              readOnly: true
      volumes:
        - name: cwagentconfig
          configMap:
            name: cwagentconfig
        - name: rootfs
          hostPath:
            path: /
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: varlibdocker
          hostPath:
            path: /var/lib/docker
        - name: sys
          hostPath:
            path: /sys
        - name: devdisk
          hostPath:
            path: /dev/disk/
      terminationGracePeriodSeconds: 60
      serviceAccountName: cloudwatch-agent
```
      
      

Error:

```
2021-07-08T00:33:57Z E! WriteToCloudWatch failure, err:  InvalidParameterValue: The parameter MetricData.member.1.Dimensions.member.4.Value must be shorter than 257 characters.
	status code: 400, request id: e9782304-e093-4fc3-9bae-4489c2d44199
2021-07-08T00:33:57Z E! WriteToCloudWatch failure, err:  InvalidParameterValue: The parameter MetricData.member.20.Dimensions.member.4.Value must be shorter than 257 characters.
	status code: 400, request id: 15a4ab27-e87f-49d1-8f2f-9cab280cf576
```
