### ISSUE TITLE
[Feature request] Support sampling of logs in CloudWatch log export

### ISSUE THREAD

**Issue by paulbrimicombe** [aws/amazon-cloudwatch-agent#257]
## Background

Currently all log lines in a log file are exported to CloudWatch logs. As log ingest costs are not negligible it is sometimes advantageous to be able to filter the log lines and only export certain log events.

Obviously this could be done in application code or in some post-processing step when the files are written but this extra effort could be avoided by adding this feature to the CloudWatch agent.

One approach might be to allow a filter pattern Regex to be included in the configuration:

```yaml
 {
  "logs": {
    "logs_collected": {
      "files": {
        "collect_list": [
          {
            "file_path": "/var/log/my-app/app.log",
            "log_group_name": "my-app-logs",
            "log_stream_name": "{instance_id}-app",
            "timestamp_format": "%Y-%m-%dT%H:%M:%S.%fZ",
            "timezone": "UTC",
            "filterPattern": "(\\\"StatusCode\\\":[4-5]\\d\\d)|(Sampled=1)"
          }
        ]
      }
    }
  }
}
```

This raises a few questions:

* What happens if the supplied pattern is not a valid Regex?
* Is Regex the best approach?
* How much will this impact performance?
