### ISSUE TITLE
Fix build & test action

### ISSUE THREAD

**Issue by jhnlsn** [aws/amazon-cloudwatch-agent#284]
Build & Test action is run 2x for every pull request where the branch is local to the repo.  I'm not sure if this is also the case when the branch is a fork.  Not sure what the right answer is yet but this config is probably causing the issue:

```
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*"]
```
