### ISSUE TITLE
Docker container does not start in EKS using Fargate

### ISSUE THREAD

**Issue by mrvisser** [aws/amazon-cloudwatch-agent#580]
**Describe the bug**
When deploying the agent container to EKS (1.23) using a fargate profile, it fails with this message:

```
  cloudwatch-agent:
    Container ID:   containerd://93bf59c3c798cc6f78343faa9cdbe7430900ab1102306f614c14e4969dc4c808
    Image:          amazon/cloudwatch-agent:1.247355.0b252062-amd64
    Image ID:       docker.io/amazon/cloudwatch-agent@sha256:80d37f8425f783872d68fe0eeb53b93a2e77777928556454f06b9502c5ec9835
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: failed to write "100000": write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod19ff292b-27c4-4d3e-85c7-6e19ca66b0cc/93bf59c3c798cc6f78343faa9cdbe7430900ab1102306f614c14e4969dc4c808/cpu.cfs_quota_us: invalid argument: unknown
      Exit Code:    128
      Started:      Wed, 31 Dec 1969 19:00:00 -0500
      Finished:     Mon, 29 Aug 2022 11:03:44 -0400
```

**Steps to reproduce**
I followed the steps relating to the Fargate launch type here: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights-Prometheus-Setup.html, using an EKS cluster on EKS 1.23. I haven't tried 1.22 at this point.

**What did you expect to see?**
I'd have expected this container to start up fine.

**What did you see instead?**
The error message.

**What version did you use?**
Version: `1.247355.0b252062`, `1.247355.0b252062-amd64` and `1.247355.0b252062-arm64`

**What config did you use?**
Config: N/A

**Environment**
OS: EKS 1.23 on fargate

**Additional context**

Deployment spec:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwagent-prometheus
  namespace: amazon-cloudwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cwagent-prometheus
  template:
    metadata:
      labels:
        app: cwagent-prometheus
    spec:
      containers:
        - name: cloudwatch-agent
          image: amazon/cloudwatch-agent:1.247355.0b252062
          imagePullPolicy: Always
          resources:
            limits:
              cpu:  1000m
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 200Mi
          # Please don't change below envs
          env:
            - name: CI_VERSION
              value: "k8s/1.3.11"
            - name: RUN_IN_AWS
              value: "True"
          # Please don't change the mountPath
          volumeMounts:
            - name: prometheus-cwagentconfig
              mountPath: /etc/cwagentconfig
            - name: prometheus-config
              mountPath: /etc/prometheusconfig
      volumes:
        - name: prometheus-cwagentconfig
          configMap:
            name: prometheus-cwagentconfig
        - name: prometheus-config
          configMap:
            name: prometheus-config
      terminationGracePeriodSeconds: 60
      serviceAccountName: cwagent-prometheus
```

Failed pod description:

```
Name:                 cwagent-prometheus-6475d78897-jm22x
Namespace:            amazon-cloudwatch
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 fargate-ip-10-0-6-68.us-east-2.compute.internal/10.0.6.68
Start Time:           Mon, 29 Aug 2022 11:03:25 -0400
Labels:               app=cwagent-prometheus
                      eks.amazonaws.com/fargate-profile=main
                      pod-template-hash=6475d78897
Annotations:          CapacityProvisioned: 0.25vCPU 0.5GB
                      Logging: LoggingDisabled: LOGGING_CONFIGMAP_NOT_FOUND
                      kubernetes.io/psp: eks.privileged
Status:               Running
IP:                   10.0.6.68
IPs:
  IP:           10.0.6.68
Controlled By:  ReplicaSet/cwagent-prometheus-6475d78897
Containers:
  cloudwatch-agent:
    Container ID:   containerd://93bf59c3c798cc6f78343faa9cdbe7430900ab1102306f614c14e4969dc4c808
    Image:          amazon/cloudwatch-agent:1.247355.0b252062-amd64
    Image ID:       docker.io/amazon/cloudwatch-agent@sha256:80d37f8425f783872d68fe0eeb53b93a2e77777928556454f06b9502c5ec9835
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: failed to write "100000": write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod19ff292b-27c4-4d3e-85c7-6e19ca66b0cc/93bf59c3c798cc6f78343faa9cdbe7430900ab1102306f614c14e4969dc4c808/cpu.cfs_quota_us: invalid argument: unknown
      Exit Code:    128
      Started:      Wed, 31 Dec 1969 19:00:00 -0500
      Finished:     Mon, 29 Aug 2022 11:03:44 -0400
    Ready:          False
---
    Restart Count:  2
    Limits:
      cpu:     1
      memory:  1000Mi
    Requests:
      cpu:     200m
      memory:  200Mi
    Environment:
      CI_VERSION:                   k8s/1.3.11
      RUN_IN_AWS:                   True
      AWS_STS_REGIONAL_ENDPOINTS:   regional
      AWS_DEFAULT_REGION:           us-east-2
      AWS_REGION:                   us-east-2
      AWS_ROLE_ARN:                 arn:aws:iam::<redacted>:role/eksctl-<redacted>-addon-iamservicea-Role1-1ZQQ37G9IUEF
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /etc/cwagentconfig from prometheus-cwagentconfig (rw)
      /etc/prometheusconfig from prometheus-config (rw)
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-6npnt (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  aws-iam-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  86400
  prometheus-cwagentconfig:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-cwagentconfig
    Optional:  false
  prometheus-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-config
    Optional:  false
  kube-api-access-6npnt:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason           Age                From               Message
  ----     ------           ----               ----               -------
  Warning  LoggingDisabled  89s                fargate-scheduler  Disabled logging because aws-logging configmap was not found. configmap "aws-logging" not found
  Normal   Scheduled        40s                fargate-scheduler  Successfully assigned amazon-cloudwatch/cwagent-prometheus-6475d78897-jm22x to fargate-ip-10-0-6-68.us-east-2.compute.internal
  Normal   Pulled           36s                kubelet            Successfully pulled image "amazon/cloudwatch-agent:1.247355.0b252062-amd64" in 2.918018615s
  Normal   Pulled           35s                kubelet            Successfully pulled image "amazon/cloudwatch-agent:1.247355.0b252062-amd64" in 213.214317ms
  Normal   Pulling          22s (x3 over 39s)  kubelet            Pulling image "amazon/cloudwatch-agent:1.247355.0b252062-amd64"
  Normal   Created          22s (x3 over 35s)  kubelet            Created container cloudwatch-agent
  Normal   Pulled           22s                kubelet            Successfully pulled image "amazon/cloudwatch-agent:1.247355.0b252062-amd64" in 217.488977ms
  Warning  Failed           21s (x3 over 35s)  kubelet            Error: failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: failed to write "100000": write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod19ff292b-27c4-4d3e-85c7-6e19ca66b0cc/cloudwatch-agent/cpu.cfs_quota_us: invalid argument: unknown
  Warning  BackOff          6s (x4 over 34s)   kubelet            Back-off restarting failed container
```
