### ISSUE TITLE
Prometheus metrics are not being send via the cloud watch agent on EMR

### ISSUE THREAD

**Issue by voropaevp** [aws/amazon-cloudwatch-agent#616]
**Describe the bug**
I am trying to get metrics from jmx_export into the cloudwatch on the EMR cluster. But CW agent doesn't send anything. JMX exporter is working correctly.

Here is jmx exporter output:
```
$ curl 127.0.0.1:8080
# HELP jvm_memory_objects_pending_finalization The number of objects waiting in the finalizer queue.
# TYPE jvm_memory_objects_pending_finalization gauge
jvm_memory_objects_pending_finalization 0.0
# HELP jvm_memory_bytes_used Used bytes of a given JVM memory area.
# TYPE jvm_memory_bytes_used gauge
jvm_memory_bytes_used{area="heap",} 4.0390928E7
...
```

Prometheus config
```yaml
cat /opt/aws/amazon-cloudwatch-agent/var/prometheus.yaml
global:
  scrape_interval: 5s
  scrape_timeout: 10s
scrape_configs:
  - job_name: jmx
    sample_limit: 10000
    static_config:
      targets: [ '127.0.0.1:8080' ]
      labels:
        emr-cluster: 'test'
```

CW agent config:
```json
{
  "agent": {
    "debug": true
  },
  "logs": {
    "metrics_collected": {
      "prometheus": {
        "log_group_name": "emr-prometheus",
        "prometheus_config_path": "/opt/aws/amazon-cloudwatch-agent/var/prometheus.yaml"
        }
    },
    "force_flush_interval": 5
  }
}
```

Log group is not created, cloud watch agent logs don't show anything except for empty buffer messages. 

**Steps to reproduce**

- download jmx_prometheus_javaagent onto the EMR cluster
- configure spark-defaults -javaagent:/etc/prometheus/jmx_prometheus_javaagent-{JMX_PROMETHEUS_VERSION}.jar=8080:/etc/prometheus/spark.yaml"
-install cloudwatch agent

**What did you expect to see?**
Log group created with raw prometheus events.

**What did you see instead?**
No log groups/metrics

**What version did you use?**
amazon-cloudwatch-agent-1.247354.0b251981-1.amzn2.x86_64

**Environment**
AWS EMR node with 4.14.291-218.527.amzn2.x86_64

**Additional context**
Other(non-prometheus) metrics are sent without any issues from the same node.

I dropped `emf_exporter` part as it wasn't working either. 
```json
"emf_processor": {
          "metric_declaration_dedup": true,
          "metric_namespace": "CWAgent-Prometheus",
          "metric_unit": {
            "jvm_threads_current$": "Count"
          },
          "metric_declaration": [
            {
              "source_labels": ["job"],
              "label_matcher": "^jmx$",
              "dimensions": [
                [
                  "emr-cluster"
                ]
              ],
              "metric_selectors": [
                "^jvm_threads_current$"
              ]
            }
    ```
