### ISSUE TITLE
Prometheus scraping produces EMF with more than 100 MetricDefinition objects, resulting in dropped metrics.

### ISSUE THREAD

**Issue by cedriclaudrel** [aws/amazon-cloudwatch-agent#664]
Hello,

**Issue summary**
While investigating an issue where many metrics where silently dropped, while being correctly exported by the prometheus exporter, and correctly scrapped, we found that (at least in our case), cloudwatch-agent doesn't respect the EMF specification.

**Steps to reproduce**
Deploy a Varnish instance (in our case on ECS, but it doesn't matter here), and a [varnish-exporter](https://github.com/jonnenauha/prometheus_varnish_exporter) along with it.
This exporter produces a great amount of metrics, many of them not having any specific label.

Scrape this exporter with CWA, using this prometheus configuration :

```yaml
global:
  scrape_interval: 1m
  scrape_timeout: 10s
scrape_configs:
  - job_name: prometheus-static
    sample_limit: 10000
    static_configs:
      - targets:
          - "127.0.0.1:9131" # Varnish
        labels:
          ClusterName: ${ECS_CLUSTER_NAME}
          ServiceName: ${ECS_SERVICE_NAME}
```
And this Cloudwatch configuration:

```json
{
  "agent": {
    "omit_hostname": true
  },
  "logs": {
    "metrics_collected": {
      "prometheus": {
        "prometheus_config_path": "/config/prometheus.yaml",
        "emf_processor": {
          "metric_declaration_dedup": true,
          "metric_declaration": [
            {
              "source_labels": [
                "job"
              ],
              "label_matcher": "prometheus-static",
              "metric_selectors": [
                "^varnish_.*$"
              ],
              "dimensions": [
                [
                  "ClusterName",
                  "ServiceName"
                ]
              ]
            }
          ]
        }
      }
    },
    "force_flush_interval": 5
  }
}
```

Then, you will find that you get many `varnish_` metrics in Cloudwatch, but a lot will also be missing.

After deeper investigation, we found that CWA produces EMF files by grouping all prometheus metric having the same tag set.
For many metrics, it's ok since they are grouped in small batches.

But there is a specific occurence, the one where metrics have no tag (besides job/instance), where this results in adding 107 metrics in the EMF log json. (I attached an EMF log event showing the issue: [emf_extract.txt](https://github.com/aws/amazon-cloudwatch-agent/files/10338216/emf_extract.txt))
This doesn't respect the [EMF spec](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html): 

> Metrics— An array of [MetricDefinition](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html#CloudWatch_Embedded_Metric_Format_Specification_structure_metricdefinition) objects. This array MUST NOT contain more than 100 MetricDefinition objects.

So, these metrics are then simply dropped by the Cloudwatch EMF parser.

**Workaround**

We managed to reduce this big batch of metrics by adding a specific label to a subset of them in the prometheus scraping configuration:

```yaml
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "varnish_main_sc_.*"
        action: "replace"
        target_label: "dummy_split"
        replacement: "main_sc"
```

This `dummy_split` label is not used later for any purpose, but has the effect of grouping all `varnish_main_sc_.*` metrics in another EMF json.
That way, the biggest EMF log event is reduced to less than 100 metrics and is then correctly ingested by Cloudwatch metrics.

To properly fix this issue, I suggest that cloudwatch-agent automatically flushes an EMF log event once it reaches 100 metrics, and then starts with a new one.

**What version did you use?**
Cloudwatch-agent `2.2.51-14.amzn2` on AmazonLinux 2.
