### ISSUE TITLE
Prometheus scrape config labels are not applied and cannot be used in metric_declaration of CW agent config

### ISSUE THREAD

**Issue by richturner** [aws/amazon-cloudwatch-agent#751]
**Describe the bug**

Prometheus scrape config labels (which should be applied to all metric in the job) don't seem to actually be applied by the cloudwatch agent because if you try using them in the `prometheus` config section of CW agent config the metrics are no longer output in the logs.

**Steps to reproduce**

### `prometheus.yaml`
```yaml
global:
  scrape_interval: 1m
  scrape_timeout: 10s
scrape_configs:
  - job_name: manager
    sample_limit: 10000
    static_configs:
      - targets:
          - localhost:8404
      - labels:
          service: manager
          test: helloworld
```

### Cloudwatch agent config
```json
{
  "logs": {
    "metrics_collected": {
      "prometheus":{
         "log_group_name":"Prometheus-Test",
         "prometheus_config_path":"/opt/aws/amazon-cloudwatch-agent/var/prometheus.yaml",
         "emf_processor":{
            "metric_declaration_dedup":true,
            "metric_namespace":"CWAgent-Prometheus-Test",
            "metric_declaration":[
               {
                  "source_labels":["job"],
                  "label_matcher":"^manager$",
                  "dimensions":[
                    ["test", "type", "id"]
                  ],
                  "metric_selectors":[
                    "^.*$"
                  ]
               }
           ]
        }
     }
  }
}
}
```

**What did you expect to see?**
Expect the label to be applied to all metrics and then that label can be used in a `metric_declaration` so cloud watch logs then contain these metrics with the custom dimension (as described in the documentation).

**What did you see instead?**
Cloud watch logs contain no metrics; if the `test` dimension is removed from the `metric_declaration` then the metrics are output in the logs as expected.

**What version did you use?**
`CWAgent/1.247359.0 (go1.19.7; linux; arm64) No Build Date`

**Environment**
Amazon Linux 2 on ARM64 EC2

**Comment by richturner** [comment]
For anyone else facing this a workaround is to use a `metric_relabel_config` like this:

```yaml
      - action: replace
        source_labels: [test]
        regex: '(.*)'
        replacement: 'VALUE_HERE'
        target_label: test
```
